### ISSUE TITLE
heading/yaw error without Magnetic data

### ISSUE THREAD

**Issue by wolf943134497** [dlaidig/vqf#11]
hi @dlaidig   Thanks for your great works and released code!
When there is no magnetometer data，can the VQF algorithm improve the accuracy of heading angle estimation? 
If this scenario has been tested, what is the accuracy improvement?
Thanks a lot!

**Comment by dlaidig** [comment]
Thank you for your interest in VQF.

Without magnetometer data, the heading angle has an arbitrary and slowly drifting offset since there is no reference for the north direction. This is true for all orientation estimation algorithms, including VQF. The arbitrary offset depends on the initialization and can be regarded as random.

The only thing where different algorithms can differ is the speed at which this offset drifts. This mostly depends on the amount of gyroscope bias in the vertical direction. I can imagine that there also might be slight differences between different algorithms due to some indirect effects in the algorithm design, but I'm not aware of any systematic comparison of this effect.

So the main effect is gyroscope bias. If the gyroscope bias is very small, this heading drift will be slow. VQF includes a gyroscope bias estimation method, which is also evaluated i[n Section 3.5 of the paper](https://arxiv.org/pdf/2203.17024.pdf). In this regard, one could argue that VQF can provide better heading angle estimates and indirectly back this up with the experimental evaluation.

I hope this clarifies things.
